### ISSUE TITLE
Provide list of nodes for warning about entrances not in stop_area relations

### ISSUE THREAD

**Issue by disc12** [mapsme/subways#36]
http://osmz.ru/subways/malaysia.html

Warning states:
"31 subway entrances are not in stop_area relations" but no nodes listed

**Comment by Zverik** [comment]
The list might be quite big, that's why I am not listing each node. I'd recommend not to fix these one by one, but use an overpass query from JOSM, something like `railway=subway_entrance or public_transport=stop_area` (type it into the overpass query wizard, after enabling "expert mode"). Then search (Ctrl+F) for `subway_entrance -child stop_area` and either add these to existing stop_areas or create new relations. For that, I recommend adding a stop_area preset to the JOSM toolbar.
